"""Script Generator agent (D2) — Generation pair · branch feat/discovery_agent.

Turns the `Flow` produced by Discovery into a runnable Playwright `Script`.

Contract with the Execution node (D3, Engine)
---------------------------------------------
`Script.code` is a Python module string defining exactly one function:

    def run(page):
        ...

Execution execs the code and calls `run(page)` with a live Playwright page. Any exception
raised inside `run` is what Diagnosis later classifies.

Deterministic by design: one `Step` → one line of Playwright. Same Flow → identical Script,
so the demo never flakes on generation.
"""
from __future__ import annotations

from schemas import AgentState, Flow, Script

DEFAULT_TIMEOUT_MS = 60_000


def _render_step(step) -> str:
    """Map one typed Step to one line of Playwright code."""
    if step.action == "goto":
        return f"    page.goto({step.value!r}, timeout={DEFAULT_TIMEOUT_MS})"
    if step.action == "fill":
        return f"    page.fill({step.selector!r}, {step.value!r})"
    if step.action == "click":
        return f"    page.click({step.selector!r})"
    if step.action == "select":
        return f"    page.select_option({step.selector!r}, {step.value!r})"
    if step.action == "expect_visible":
        return f"    page.wait_for_selector({step.selector!r}, timeout={DEFAULT_TIMEOUT_MS})"
    raise ValueError(f"unknown action '{step.action}' in step: {step.description!r}")


def render_script(flow: Flow) -> str:
    """Deterministic Flow → Playwright module string. Pure function, easy to test."""
    lines = [
        "# AUTO-GENERATED by Script Generator (D2). Do not edit by hand.",
        f"# flow: {flow.id} — {flow.name}",
        "",
        "def run(page):",
    ]
    for step in flow.steps:
        if step.description:
            lines.append(f"    # {step.description}")
        lines.append(_render_step(step))
    lines.append("")
    return "\n".join(lines)


def script_gen_node(state: AgentState) -> dict:
    """LangGraph node. Requires state.flow (Discovery runs first).

    Returns a partial state update ({"script": ...}); LangGraph merges it into AgentState.
    """
    if state.flow is None:
        raise ValueError("script_gen_node needs state.flow — run discovery_node first")

    # >>> OUTPUT TO THE EXECUTION AGENT (D3, Engine) <<<
    # This Script is what Execution consumes: it execs `script.code` (a module defining
    # `def run(page): ...`) and calls run(page) against a live Playwright page.
    # `script.code`  -> the generated Playwright script (str)
    # `script.flow_id` -> which discovered flow it came from (traceability)
    # Reached in the graph via:  state.script  (after the script_gen -> execution edge)
    return {"script": Script(flow_id=state.flow.id, code=render_script(state.flow))}
