"""Deterministic LLM mock (B3) — Healing pair · usable from hour 0.

Returns canned typed responses so every lane can build without hitting OpenRouter.
Set USE_MOCK=1 in the environment to route model_for() through this.

Role-aware responses:
  "diagnosis" → JSON string matching the Diagnosis schema (one per ErrorKind)
  "repair"    → a minimal valid Playwright Python script string
  anything else → generic mock string
"""
from __future__ import annotations

import json

# ---------------------------------------------------------------------------
# Canned Diagnosis responses — one per ErrorKind.
# The diagnosis node reads `state.result.error.kind` to pick the right one.
# ---------------------------------------------------------------------------
_DIAGNOSIS_CANNED: dict[str, dict] = {
    "selector": {
        "root_cause": (
            "The CSS/data-test selector no longer matches any element on the page. "
            "The attribute value or element type was likely renamed in a recent UI update."
        ),
        "confidence": 0.92,
        "suggested_fix": (
            "Inspect the current DOM and update the selector. "
            "Prefer [data-test='...'] attributes over class or id selectors for stability."
        ),
    },
    "timeout": {
        "root_cause": (
            "The page or element did not become visible within the configured timeout. "
            "Possible causes: slow network, server-side rendering delay, or a missing loader guard."
        ),
        "confidence": 0.85,
        "suggested_fix": (
            "Increase the wait timeout to 10 000 ms and add an explicit "
            "page.wait_for_load_state('networkidle') before the failing action."
        ),
    },
    "missing_element": {
        "root_cause": (
            "The expected element is absent from the DOM entirely. "
            "It may be conditionally rendered or removed in this user-role context."
        ),
        "confidence": 0.88,
        "suggested_fix": (
            "Add a conditional check (page.is_visible) before interacting. "
            "Ensure the logged-in user role has access to this UI component."
        ),
    },
    "flow_change": {
        "root_cause": (
            "The application flow has changed: a step has been reordered, renamed, or "
            "split into multiple sub-steps compared to the original script."
        ),
        "confidence": 0.80,
        "suggested_fix": (
            "Re-map the flow from the current page structure. "
            "Update the step sequence so each action targets the correct page state."
        ),
    },
}

# ---------------------------------------------------------------------------
# Canned Repair response — a minimal Playwright script skeleton.
# The repair node replaces the broken script code with this as a starting point.
# ---------------------------------------------------------------------------
_REPAIR_CANNED = """\
from playwright.sync_api import sync_playwright

def run():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        # --- repaired script generated by Adaptive Repair agent ---
        page.goto("https://www.saucedemo.com/")
        page.wait_for_load_state("networkidle")
        page.fill("[data-test='username']", "standard_user")
        page.fill("[data-test='password']", "secret_sauce")
        page.click("[data-test='login-button']")
        page.wait_for_selector("[data-test='inventory-container']", timeout=10000)
        page.click("[data-test='add-to-cart-sauce-labs-backpack']")
        page.click("[data-test='shopping-cart-link']")
        page.click("[data-test='checkout']")
        page.fill("[data-test='firstName']", "Test")
        page.fill("[data-test='lastName']", "User")
        page.fill("[data-test='postalCode']", "12345")
        page.click("[data-test='continue']")
        page.click("[data-test='finish']")
        page.wait_for_selector("[data-test='complete-header']", timeout=10000)
        browser.close()

if __name__ == "__main__":
    run()
"""


class FakeModel:
    """A drop-in replacement for a LangChain chat model that returns canned content."""

    def __init__(self, role: str = "default") -> None:
        self.role = role

    def invoke(self, messages, **_kwargs) -> "_Msg":
        content = self._content_for_role(messages)
        return _Msg(content)

    def _content_for_role(self, messages) -> str:
        if self.role == "repair":
            return _REPAIR_CANNED

        if self.role == "diagnosis":
            # Try to infer the ErrorKind from the message text so tests can be specific.
            text = _flatten_messages(messages)
            for kind in ("selector", "timeout", "missing_element", "flow_change"):
                if kind in text:
                    return json.dumps(_DIAGNOSIS_CANNED[kind])
            # Default to "selector" if we can't detect the kind.
            return json.dumps(_DIAGNOSIS_CANNED["selector"])

        # Generic fallback for discovery, script_gen, etc.
        return f"mock-response for role={self.role}"


class _Msg:
    """Minimal stand-in for a LangChain AIMessage."""

    def __init__(self, content: str) -> None:
        self.content = content

    def __repr__(self) -> str:  # pragma: no cover
        return f"_Msg(content={self.content!r})"


def fake_model_for(role: str) -> FakeModel:
    """Return a FakeModel configured for the given agent role."""
    return FakeModel(role=role)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _flatten_messages(messages) -> str:
    """Convert whatever message format LangChain passes to a single lowercase string."""
    if isinstance(messages, str):
        return messages.lower()
    if isinstance(messages, list):
        parts = []
        for m in messages:
            if isinstance(m, str):
                parts.append(m)
            elif hasattr(m, "content"):
                parts.append(str(m.content))
            else:
                parts.append(str(m))
        return " ".join(parts).lower()
    return str(messages).lower()
